import type { NetworkSnapshot } from "../types";
export function generateMockSnapshot(): NetworkSnapshot {
  const t = Date.now() / 1000;
  const downBase = Math.abs(Math.sin(t * 0.4)) * 14 * 1024 * 1024 + 500 * 1024;
  const upBase = Math.abs(Math.cos(t * 0.3)) * 2.5 * 1024 * 1024 + 100 * 1024;

  return {
    timestamp: Date.now(),
    total_download_speed_bps: Math.round(downBase),
    total_upload_speed_bps: Math.round(upBase),
    total_active_connections: 18,
    interfaces: [
      {
        id: "if-1",
        name: "Intel(R) Wi-Fi 6E AX211 160MHz",
        alias: "Wi-Fi",
        interface_type: "wifi",
        status: "connected",
        ipv4: "192.168.1.145",
        ipv6: null,
        download_speed_bps: Math.round(downBase),
        upload_speed_bps: Math.round(upBase),
        driver: {status: "available", sampled_at: Date.now(), value: {source: "windows_cim_win32_pnpsigneddriver", provider: "Example adapter vendor", version: "1.2.3.4", date: "2026-01-01"}},
        details: {
          source: "windows_mib_if_row2", interface_guid: "00000000-0000-0000-0000-000000000001", interface_index: 1,
          mtu_bytes: 1500, operational_status: "up", administrative_status: "up", media_state: "connected",
          interface_type_code: 71, physical_medium_code: 9, tunnel_type_code: 0, hardware_interface: true,
          connector_present: true, filter_interface: false, paused: false, low_power: false,
          counters: {received_bytes: "450000000", sent_bytes: "12000000", received_unicast_packets: "320000", sent_unicast_packets: "18000", received_non_unicast_packets: "150", sent_non_unicast_packets: "80", receive_errors: "0", transmit_errors: "0", receive_discards: "0", transmit_discards: "0", unknown_protocol_packets: "0"},
        },
        ip_configuration_status: "available",
        ip_configuration: {source: "windows_get_adapters_addresses", sampled_at: Date.now(), addresses: [{address: "192.0.2.10", prefix_length: 24, family: "ipv4"}], dns_servers: ["192.0.2.1"], gateways: ["192.0.2.1"], dhcpv4_enabled: true, dhcpv4_server: "192.0.2.1", dhcpv6_server: null, ipv4_metric: 25, ipv6_metric: 25},
        route_configuration_status: "available",
        route_configuration: {source: "windows_get_ip_forward_table2", sampled_at: Date.now(), routes: [{destination: "0.0.0.0", prefix_length: 0, family: "ipv4", next_hop: "192.0.2.1", route_metric: 0, protocol_code: 3, origin_code: 2, is_default: true, valid_lifetime_seconds: null}]},
        receive_link_speed_bps: 1_200_000_000,
        transmit_link_speed_bps: 1_200_000_000,
        is_default_gateway: true,
      },
    ],
    processes: [
      {
        pid: 14220,
        name: "chrome.exe",
        path: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
        icon_data_url: null,
        download_speed_bps: Math.round(downBase * 0.8),
        upload_speed_bps: Math.round(upBase * 0.3),
        total_bytes_received: 450000000,
        total_bytes_sent: 12000000,
        active_sockets_count: 8,
        is_blocked: false,
        is_system: false,
        has_external_traffic: true,
        has_unencrypted_traffic: false,
        sockets: [
          {
            id: "tcp4-14220-1",
            protocol: "TCP",
            state: "ESTABLISHED",
            local_ip: "192.168.1.145",
            local_port: 54312,
            remote_ip: "142.250.180.14",
            remote_port: 443,
            remote_host: "video.google.com",
            country_code: "US",
            country_name: "United States",
            cloud_provider: "Google Cloud",
            service_tag: "HTTPS",
            is_tls: true,
            is_local: false,
            is_muted: false,
            download_speed_bps: Math.round(downBase * 0.75),
            upload_speed_bps: Math.round(upBase * 0.2),
          },
          {
            id: "tcp4-14220-2",
            protocol: "TCP",
            state: "ESTABLISHED",
            local_ip: "192.168.1.145",
            local_port: 54316,
            remote_ip: "104.16.12.34",
            remote_port: 443,
            remote_host: "cdnjs.cloudflare.com",
            country_code: "US",
            country_name: "United States",
            cloud_provider: "Cloudflare",
            service_tag: "HTTPS",
            is_tls: true,
            is_local: false,
            is_muted: false,
            download_speed_bps: 24000,
            upload_speed_bps: 1200,
          },
        ],
      },
      {
        pid: 9812,
        name: "Discord.exe",
        path: "C:\\Users\\Example\\AppData\\Local\\Discord\\app-1.0.9000\\Discord.exe",
        icon_data_url: null,
        download_speed_bps: Math.round(downBase * 0.12),
        upload_speed_bps: Math.round(upBase * 0.5),
        total_bytes_received: 85000000,
        total_bytes_sent: 45000000,
        active_sockets_count: 4,
        is_blocked: false,
        is_system: false,
        has_external_traffic: true,
        has_unencrypted_traffic: false,
        sockets: [
          {
            id: "tcp4-9812-1",
            protocol: "TCP",
            state: "ESTABLISHED",
            local_ip: "192.168.1.145",
            local_port: 58210,
            remote_ip: "162.158.20.10",
            remote_port: 443,
            remote_host: "gateway.discord.gg",
            country_code: "US",
            country_name: "United States",
            cloud_provider: "Discord",
            service_tag: "HTTPS",
            is_tls: true,
            is_local: false,
            is_muted: false,
            download_speed_bps: 85000,
            upload_speed_bps: 45000,
          },
        ],
      },
      {
        pid: 4,
        name: "System",
        path: "C:\\Windows\\System32\\ntoskrnl.exe",
        icon_data_url: null,
        download_speed_bps: 2048,
        upload_speed_bps: 1024,
        total_bytes_received: 1200000,
        total_bytes_sent: 800000,
        active_sockets_count: 5,
        is_blocked: false,
        is_system: true,
        has_external_traffic: false,
        has_unencrypted_traffic: false,
        sockets: [
          {
            id: "tcp4-4-1",
            protocol: "TCP",
            state: "ESTABLISHED",
            local_ip: "192.168.1.145",
            local_port: 445,
            remote_ip: "192.168.1.1",
            remote_port: 445,
            remote_host: "router.local",
            country_code: "LAN",
            country_name: "Local Network",
            cloud_provider: "Local Network",
            service_tag: "SMB",
            is_tls: false,
            is_local: true,
            is_muted: false,
            download_speed_bps: 2048,
            upload_speed_bps: 1024,
          },
        ],
      },
    ],
  };
}
